version: "3.3"

services:
  api:
    build: ./node
    image: vivekrahul/docker-practice_api:docker-practice_api
    ports:
      - 5002:5002
    depends_on:
      - db
  db:
    image: "vivekrahul/mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Welcome@123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
